# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21cc5471aafb4b4d8173530ae0b62a8eff2fd2c3ff50a6fea3c14869afa9936a75cb97759425f76c8d6b020ac6f2bf88b688d5cd502ed3a2e6540fa406ba1b6b

test:
  secret_key_base: 5eb36890a97b548008f3a31e87f35179346f458e446d35e60a809b55c821c9deea4722df6bde7cb596c8df54d3e2121516fbb9551f522e4bc3a9a39cc5214c1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
